---
- name: restart oracle listener
  ansible.builtin.shell:
    cmd: |
      set -uo pipefail
      export ORACLE_HOME="{{ oracle_home }}"
      export PATH="$ORACLE_HOME/bin:$PATH"
      lsnrctl stop  || true
      sleep 3
      lsnrctl start
  become: true
  become_user: oracle
  changed_when: true
