---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart lan forward
  ansible.builtin.systemd:
    name: wls-lan-forward.service
    state: restarted
  become: true
