#!/usr/bin/env bash
#
# Generate and persist the database credentials used by Ansible.
#
# WHY THIS EXISTS
# Passing freshly generated passwords inline (-e "oracle_app_password=$(openssl
# rand ...)") loses them the moment the command finishes. The application deploy
# stage runs LATER and needs the SAME app password to build web.xml, so an
# inline value silently produces an app that cannot authenticate to the database.
#
# Credentials are written root-readable only, outside the repo, and are
# .gitignore'd anyway. They are never echoed.
#
set -euo pipefail

SECRETS_DIR="${SECRETS_DIR:-$HOME/.homelab-iac}"
SECRETS_FILE="$SECRETS_DIR/db-credentials.yml"

mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

if [ -f "$SECRETS_FILE" ]; then
    echo "credentials already exist: $SECRETS_FILE"
    echo "delete the file to rotate (this will NOT update an existing database)"
    exit 0
fi

# Oracle requires: >= 8 chars, at least one letter, digit and permitted symbol.
# Avoid / + = @ " ' which break sqlplus connect strings and shell quoting.
#
# CRITICAL: the password must NOT start with a digit. Oracle rejects such values
# with DBT-05509 / INVALID_USER_INPUT during dbca, because an unquoted
# identifier beginning with a number is invalid. `openssl rand | tr -dc` happily
# produces one about 15% of the time, which makes the failure intermittent and
# baffling. Force a leading letter.
gen() { printf 'A%s' "$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 17)"; }

SYS_PW="$(gen)aA1"
APP_PW="$(gen)aA1"

umask 077
cat > "$SECRETS_FILE" <<EOF
# Generated by scripts/gen-db-credentials.sh — DO NOT COMMIT.
# Consumed via: ansible-playbook -e @$SECRETS_FILE
oracle_sys_password: "$SYS_PW"
oracle_app_password: "$APP_PW"
EOF
chmod 600 "$SECRETS_FILE"

echo "credentials written to $SECRETS_FILE (mode 600)"
echo "use with:  ansible-playbook playbooks/site.yml -e @$SECRETS_FILE"
